.TH KSMBDPWD.DB "5" "" "ksmbd-tools 4.2.12" "File Formats and Conventions"
.SH NAME
ksmbdpwd.db \- the user database used by ksmbdctl
.SH DESCRIPTION
\fBksmbdpwd.db\fR is the user database for the ksmbd userspace daemon.
\fBksmbdctl user\fR may be used for configuring users in \fBksmbdpwd.db\fR.
\fBksmbdctl user\fR notifies the daemon of changes, if it had made any, by sending \fBSIGHUP\fR.
\fBksmbdctl reload\fR can be used for notifying the daemon of changes when not using \fBksmbdctl user\fR.
\fBksmbdpwd.db\fR is expected to be at \fB/usr/local/etc/ksmbd/ksmbdpwd.db\fR by default. \" PATH_PWDDB
.SH "FILE FORMAT"
\fBksmbdpwd.db\fR consists of users separated by newlines.
Each user consists of a name and a password, in that order, separated by a colon (\fB:\fR).
The name must be UTF-8 and [1, 48) bytes. \" KSMBD_REQ_MAX_ACCOUNT_NAME_SZ
The password is created from the user-input UTF-8 password, [0, 129) bytes, by converting it to UTF-16LE, then MD4-hashing it, and finally Base64-encoding and padding it. \" MAX_NT_PWD_LEN
.SH COPYRIGHT
Copyright \(co 2015-2022 ksmbd-tools contributors.
License GPLv2: GNU GPL version 2 <https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "REPORTING BUGS"
For bug reports, use the issue tracker at https://github.com/cifsd-team/ksmbd-tools/issues.
.SH "SEE ALSO"
.TP
\fBUtilities\fR
\fBksmbdctl\fR(8)
